Added options -q/--quiet and -s/--stop-on-first-error to the run_tests.sh script. Also, -h/-help/--help now prints  a short usage.

diff --git a/tp04/cmake/run_tests.sh.in b/tp04/cmake/run_tests.sh.in
--- a/tp04/cmake/run_tests.sh.in
+++ b/tp04/cmake/run_tests.sh.in
@@ -1,10 +1,31 @@
 # !/bin/bash
 
-if [ $# > 0 ]
-then
-    filter=-DFILTER="$1"
-else
-    filter=
-fi
 
-cmake -DTARGETS="@all_tests@" -DBUILD_PATH="@CMAKE_BINARY_DIR@" $filter -P "@CMAKE_CURRENT_SOURCE_DIR@/cmake/run_tests.cmake"
+sFLAG=""
+qFLAG=""
+filter=""
+while [ $# -gt 0 ]                                                               
+do                                                                               
+    case "$1" in
+        -h | -help | --help )
+            echo "Usage: run_tests.sh [-q] [-s] [optional pattern]";
+            echo " -q / --quiet:  Output of failed tests is not printed.";                           
+            echo " -s / --stop-on-first-error:  The program stops as soon as one test fails, skipping remaining tests.";
+            exit 1;;
+        --stop-on-first-error | -s ) 
+            sFLAG="-DSTOP_ON_ERROR=1" ;;                                                                 
+        --quiet | -q ) 
+            qFLAG="-DQUIET=1" ;;
+        -qs | -sq )
+            sFLAG="-DSTOP_ON_ERROR=1";
+            qFLAG="-DQUIET=1" ;;
+        -* ) 
+            echo "Unrecognized option ${1}";
+            exit 2;;                                                                                                                           
+        * )   
+            filter=-DFILTER="$1";;                                         
+    esac                                                                         
+    shift                                                                        
+done   
+
+cmake -DTARGETS="@all_tests@" -DBUILD_PATH="@CMAKE_BINARY_DIR@" $sFLAG $qFLAG $filter -P "@CMAKE_CURRENT_SOURCE_DIR@/cmake/run_tests.cmake"
